### ISSUE TITLE
Document this project's relationship to and/or migrateability from mongobee

### ISSUE THREAD

**Issue by mjustin** [cloudyrock/mongock#224]
When looking for options to upgrade [mongobee](https://github.com/mongobee/mongobee) (more specifically, the [MongobeeJ](https://github.com/cybuch/mongobeeJ) fork) to something that supports the latest Spring Boot/Mongo Java 4 drivers, I didn't look too closely at Mongock at first.  It wasn't immediately clear that it was a fork of the original Mongobee, and thus actually very closely related in both conceptual and implementation details.  It also wasn't clear that it supported a very straightforward migration path from Mongobee right out of the box.  It's also harder to find when Googling for "Mongobee", since it doesn't mention it in its documentation.

It might be worth calling out the relation to/migration path from Mongobee in the project readme, to aid other users in a similar situation.

Note: There are at least three Mongobee forks out there right now, so making the situation as clear as possible to users with similar upgrade needs is probably a win all around.

* [mongobee](https://github.com/mongobee/mongobee) - The original.  Maintained from 2014 - 2017.  Appears to be abandoned, hence the multiple forks.
* [Mongock](https://github.com/cloudyrock/mongock) - This project. Forked from Mongobee in 2018.  Actively maintained.  Now with Mongo Java Driver 4 support.
* [mongobeeJ](https://github.com/cybuch/mongobeeJ) - Forked from Mongobee in 2018.  Three releases from 2018 - 2019.
* [dalet-oss/mongobee](https://github.com/dalet-oss/mongobee) - Forked from Mongobee in June 2020 (a month and a half ago).  Its owners [have stated](https://github.com/mongobee/mongobee/issues/116#issue-636808652) that they intend to continue maintaining this fork, though it is still too early to see how this will play out.

**Comment by dieppa** [comment]
Thanks @mjustin, I think you are totally right. The natural path  for Mongobee users to be upgraded is Mongock. If we don't make it clear, they don't have an easy way to know it.

Will do that.

**Comment by mjustin** [comment]
Just noticed that 4.1.8 [split out the project documentation](https://www.mongock.io), so I guess this would live in either/both of the project [readme](https://github.com/cloudyrock/mongock/blob/master/README.md) and/or the project documentation.

Incidentally, what I've done to migrate is to point Mongock at my previous Mongobee collection/package.  I also deleted the mongobee lock collection, since Mongock has its own.  This appears to work, though I'm not sure whether this is the recommended approach (which is one thing migration documentation could aid in, now that I think about it).

### application.yml
```
spring:
  mongock:
    enabled: true
    change-logs-scan-package: com.example.my.mongobee.migrations.pkg
    change-log-collection-name: dbchangelog #Default collection name used by mongobee
```

### V20200723101500_RemoveMongobeeLock.java
```
package com.example.my.mongobee.migrations.pkg;

import com.github.cloudyrock.mongock.ChangeLog;
import com.github.cloudyrock.mongock.ChangeSet;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.mongodb.core.MongoOperations;

@Slf4j
@ChangeLog
public class V20200723101500_RemoveMongobeeLock extends MongoMigration {
    private static final String MONGOBEE_LOCK_COLLECTION_NAME = "mongobeelock";

    @ChangeSet(order = "001", id = "dropMongobeeLockCollection", author = "JDoe")
    public void dropMongobeeLockCollection(MongoOperations mongoTemplate) {
        mongoTemplate.dropCollection(MONGOBEE_LOCK_COLLECTION_NAME);
        log.info("Dropped collection {}", MONGOBEE_LOCK_COLLECTION_NAME);
    }
}
```

**Comment by dieppa** [comment]
Hello @mjustin,

actually it's not the recommended way, but we haven't documented it, although the section is ready [legacy migration](https://www.mongock.io/legacy-migration).


We'd like to have this part of the documentation ready this week, if my expectations are right, tomorrow. If for any reason you can wait, it would be great.
Otherwise, this is an example of configuration that should work:
```yaml
spring:
  mongock:
    enabled: true #you don't need this
    change-logs-scan-package: com.example.my.mongobee.migrations.pkg
    legacy-migration:
      collection-name: dbchangelog
      changes-count-expectation: 2 # this is optional and sets the changes-migration expectations. If you have 3 documents in your legacy changeLog collection, you should set this to 3
```

This should work as I think all the fields in the changeLog collection are the same. If they are not, let me know and I will paste the piece of code for that ;)
